### ISSUE TITLE
NOT public domain

### ISSUE THREAD

**Issue by Aspie96** [allthemusicllc/atm-cli#19]
> All code is released into the public domain via the Creative Commons Attribute 4.0 International License. 

The Creative Commons Attribut**ion** (not "Attribute") is NOT for public domain.
The CC0 Public Domain Declaration is for public domain.

The two are quite different.

**Comment by allthemusicllc** [comment]
@Aspie96 thank you for noting the distinction, we've fixed the excerpt you referenced, and added a clarifying section in the README in #20. We'll keep the PR open for a day or so, let us know if you have any other recommendations.

**Comment by systemed** [comment]
CC-BY isn't a code licence, it's a creative works licence. It would be better to use a well-known permissive code licence such as MIT.

You may also want to clarify that you claim no rights in the output of the program (i.e. the music itself), as that isn't currently clear from the README.

**Comment by dieterdreist** [comment]
arguably you will also have the already copyrighted melodies in the output.

**Comment by Aspie96** [comment]
There is still an issue @allthemusicllc:
> CC BY 4.0 allows us to assert that no one can place additional restrictions on derivative works,

No, it does not, because it isn't copyleft.
> You may not offer or impose any additional or different terms or conditions on, or apply any Effective Technological Measures to, the Licensed Material if doing so restricts exercise of the Licensed Rights by any recipient of the Licensed Material.

This refers to the licensed material, which is the code. Dervitavies may very well have more restrictive license.
A copyleft license is needed if you want to forbid using a more restrictive license.

As a matter of fact, maybe your code is better with a permissive license, like the current one (and I am not suggesting that you go with copyleft, expecially considering you already licensed the code and it would simply lead to a fork), but it should state "additional restrictions on the code", rather than "on derivatives".
